# Generated by Django 3.2.5 on 2021-08-16 06:57

from django.db import migrations, models
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        UnaccentExtension(),
    ]
