# Generated by Django 3.2.5 on 2021-08-22 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_unaccent_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='composition',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='store.composition'),
        ),
    ]
