# Generated by Django 3.2.5 on 2021-07-24 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_price_product_price_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.dataafterpurchase'),
        ),
    ]
