# Generated by Django 3.2.5 on 2021-08-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_composition'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataafterpurchase',
            name='youtube_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
