# Generated by Django 3.2.5 on 2021-07-25 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='authenticated data',
        ),
    ]
