# Generated by Django 3.2.5 on 2021-09-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_dataafterpurchase_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataafterpurchase',
            name='metronome_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
