# Generated by Django 3.2.5 on 2021-07-25 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_product_product_authenticated data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='authenticated data',
            new_name='authenticated_data',
        ),
    ]
