# Generated by Django 3.2.5 on 2021-07-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_authenticated_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataafterpurchase',
            name='pdf_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataafterpurchase',
            name='flac_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataafterpurchase',
            name='midi_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataafterpurchase',
            name='wav_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
