# Generated by Django 3.2.5 on 2021-07-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210726_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='free',
            field=models.BooleanField(default=False),
        ),
    ]
