# Generated by Django 3.2.5 on 2021-08-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210808_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='composer',
        ),
        migrations.AddField(
            model_name='product',
            name='composers',
            field=models.ManyToManyField(related_name='compositions', to='store.Composer'),
        ),
    ]
