# Generated by Django 3.2.5 on 2021-08-08 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210808_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='authenticated_data',
        ),
        migrations.AddField(
            model_name='dataafterpurchase',
            name='composition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='store.composition'),
        ),
    ]
