# Generated by Django 3.2.5 on 2021-08-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20210808_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataafterpurchase',
            name='flac_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dataafterpurchase',
            name='midi_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dataafterpurchase',
            name='pdf_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dataafterpurchase',
            name='wav_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
