# Generated by Django 3.2.5 on 2021-08-11 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_dataafterpurchase_composition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='composition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='store.composition'),
        ),
    ]
