# Generated by Django 3.2.5 on 2021-08-13 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_remove_cart_items_in_cart'),
        ('store', '0021_alter_product_composition'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_in_cart', to='Cart.cart'),
        ),
    ]
