# Generated by Django 3.2.5 on 2021-08-20 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_product_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='free',
        ),
    ]
