# Generated by Django 3.2.5 on 2021-08-20 13:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0023_remove_product_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataafterpurchase',
            name='purchased_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
