# Generated by Django 3.2.5 on 2021-08-20 13:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0024_dataafterpurchase_purchased_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataafterpurchase',
            name='purchased_by',
            field=models.ManyToManyField(related_name='purchased_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
