# Generated by Django 3.2.5 on 2021-08-21 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_dataafterpurchase_purchased_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataafterpurchase',
            name='composition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='store.composition'),
        ),
    ]
