# Generated by Django 3.2.5 on 2021-08-13 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_alter_cart_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items_in_cart',
        ),
    ]
