# Generated by Django 3.2.5 on 2021-08-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_remove_cart_items_in_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
