# Generated by Django 3.2.5 on 2021-08-17 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0005_alter_cart_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='date_ordered',
            new_name='date_created',
        ),
    ]
